apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: project-02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-2
      containers:
      - name: backend
        image: hashicorp/http-echo:latest
        args:
        - "-text=Hello from Backend API! - Bilal K8s Project 02"
        ports:
        - containerPort: 5678
        env:
        - name: APP_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
